version: "3.8"

services:
  web:
    build: .
    command: gunicorn --config gunicorn_config.py wsgi:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:7.0-alpine"
  celery:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A app.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
